<?php

namespace Inc\Blocks;

class Blocks
{
	function __construct()
	{
		add_action('enqueue_block_editor_assets', [$this, 'register_block_scripts']);
		add_action('init', [$this, 'register_block_types']);
	}

	/**
	 * enqueue all block script dependencies automatically generated by @wordpress/scripts package
	 */
	public function register_block_scripts()
	{
		if (!file_exists(get_template_directory() . '/build/index.asset.php')) return;

		$asset_file = include(get_template_directory() . '/build/index.asset.php');

		wp_register_script(
			'custom-blocks',
			get_template_directory_uri() . '/build/index.js',
			$asset_file['dependencies'],
			$asset_file['version']
		);
	}

	/**
	 * register blocks created in js
	 */
	public function register_block_types()
	{
		register_block_type('namespace/slug-test', [
			'editor_script' => 'custom-blocks'
		]);
	}
}
