version: '3'

services:
  wordpress:
    image: wordpress:php7.4
    ports:
      - '8069:80'
    volumes:
      - ./wp:/var/www/html/wp-content/themes/project-paradise
      - ./wp/_wp-files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1
    depends_on:
      - mysql
    networks:
      - wp

  mysql:
    image: mysql:latest
    ports:
      - '6033:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "wp"
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wp

networks:
  wp:
volumes:
  db-data:
