version: "3.3"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: wp-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - wp-db:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - wp

  wp:
    image: wordpress:latest
    container_name: wp
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wp:/var/www/html/wp-content/themes/project-paradise
      - ./wp/_wp-files:/var/www/html
    ports:
      - "${WP_PORT}:80"
    networks:
      - wp
networks:
  wp:
volumes:
  wp-db:
