export const EVENTS = {
	APP_ROOT: {
		SWIPE_SCROLL_FINISH: 'SWIPE_SCROLL_FINISH',
		SCROLL_UPDATE: 'SCROLL_UPDATE',
		TOUCH_END: 'TOUCH_END',
		MOUSE_UP: 'MOUSE_UP',
		SWIPE_X_START: 'SWIPE_X_START',
		SET_SCROLL_ENABLED: 'SET_SCROLL_ENABLED'
	},
	FIXED_BARS: {
		RIGHT_BAR_TOGGLE: 'RIGHT_BAR_TOGGLE',
		RIGHT_BAR_UPDATE: 'RIGHT_BAR_UPDATE'
	}
};
