export const FIXED_BARS = {
	SET_RIGHT_BAR_ENABLED: 'SET_RIGHT_BAR_ENABLED',
	SET_RIGHT_BAR_ACTIVE: 'SET_RIGHT_BAR_ACTIVE',
	SET_MOBILE_TOP_BAR_ENABLED: 'SET_MOBILE_TOP_BAR_ENABLED',
	SET_BOTTOM_BAR_ENABLED: 'SET_BOTTOM_BAR_ENABLED'
};