export const ACTIONS = {
	APP_ROOT: {
		SET_WIDTH_HEIGHT: 'SET_WIDTH_HEIGHT',
		SET_SCROLL_ENABLED: 'SET_SCROLL_ENABLED'
	},
	FIXED_BARS: {
		SET_RIGHT_BAR_ENABLED: 'SET_RIGHT_BAR_ENABLED',
		SET_RIGHT_BAR_ACTIVE: 'SET_RIGHT_BAR_ACTIVE'
	},
	SETTINGS: {
		SET_POSTS_PER_PAGE: 'SET_POSTS_PER_PAGE'
	}
};
